POST http://localhost:3000/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJKb2huIERvZWFzZGFzZCIsImVtYWlsIjoiam9obmRvZUBleGFtcGxlLmNvbWFzYXNkIiwiaWQiOiI2NDFmMjZjYTBhY2E3ZGMxZTEwMDJhZWQifSwiaWF0IjoxNjc5NzY0MzI3LCJleHAiOjE2Nzk3Njc5Mjd9.K2cHw-p109ZWj6ZjO78ZbVRC7VREpGkCGXt8Rh-Aqsg


{
  "name": "John Doeasdasdasd",
  "email": "johndoe@example.comasasd",
  "password": "mypasswordasdasd"
}
###

DELETE   http://localhost:3000/api/users/641f2bd6bb05571e9d0077d2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJKb2huIERvZWFzZGFzZCIsImVtYWlsIjoiam9obmRvZUBleGFtcGxlLmNvbWFzYXNkIiwiaWQiOiI2NDFmMjZjYTBhY2E3ZGMxZTEwMDJhZWQifSwiaWF0IjoxNjc5NzY0MzI3LCJleHAiOjE2Nzk3Njc5Mjd9.K2cHw-p109ZWj6ZjO78ZbVRC7VREpGkCGXt8Rh-Aqsg

{
  "name": "John Doasdasdeasdasadasdd",
  "email": "johndoe@exasdasdample.comasasdasd",
  "password": "mypasswasdadasdordasdasdasd"
}

###

GET  http://localhost:3000/api/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJSYW5hIiwiZW1haWwiOiJyYW5hQHJhbmEuY29tIiwidXNlcnR5cGUiOiJhZG1pbiIsImlkIjoiNjQyMDUxMGUyZTIzMTA0YzQzZGM3NWMzIn0sImlhdCI6MTY3OTgzOTY1NywiZXhwIjoxNjc5ODQzMjU3fQ.tL1wvvl4DFEmTbefuQDhmbfQNNEFyc8fU9qt8_b6rfY
Content-Type: application/json

{
  "name": "John Doeasdas",
  "email": "helloasd",
  "password": "mypasswordasdasd"
}
###
POST http://localhost:3000/api/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJKb2huIERvZWFzZGFzZCIsImVtYWlsIjoiam9obmRvZUBleGFtcGxlLmNvbWFzYXNkIiwiaWQiOiI2NDFmMzAyMmNhMWM5NWZmNTRhNGRlNTYifSwiaWF0IjoxNjc5ODEyMzQ3LCJleHAiOjE2Nzk4MTU5NDd9.sVYGmyORpRAKqBkGhgLgrhrcYSroXbNQ-TL4ZA13geY

{
      "title": "req.body.titleasdasd",
    "description": "req.body.descriptionasdasd"
}
###
GET http://localhost:3000/api/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJKb2huIERvZWFzZGFzZCIsImVtYWlsIjoiam9obmRvZUBleGFtcGxlLmNvbWFzYXNkIiwiaWQiOiI2NDFmMzAyMmNhMWM5NWZmNTRhNGRlNTYifSwiaWF0IjoxNjc5ODEyMzQ3LCJleHAiOjE2Nzk4MTU5NDd9.sVYGmyORpRAKqBkGhgLgrhrcYSroXbNQ-TL4ZA13geY
### 
GET  http://localhost:3000/api/tasks/641f319d1c509f97ee55f469
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJKb2huIERvZWFzZGFzZCIsImVtYWlsIjoiam9obmRvZUBleGFtcGxlLmNvbWFzYXNkIiwiaWQiOiI2NDFmMzAyMmNhMWM5NWZmNTRhNGRlNTYifSwiaWF0IjoxNjc5ODEyMzQ3LCJleHAiOjE2Nzk4MTU5NDd9.sVYGmyORpRAKqBkGhgLgrhrcYSroXbNQ-TL4ZA13geY

{
  "title": "Finish projectasdasdasdsfasd",
  "description": "Complete the project before the deadlineasdasdasdsdfsdfasd",
  "user": "60e8fa80a2e8c3143c0e5693"
}

###
DELETE http://localhost:3000/api/tasks/641f1a5e02344d509680ac5d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJKb2huIERvZWFzZGFzZCIsImVtYWlsIjoiam9obmRvZUBleGFtcGxlLmNvbWFzYXNkIiwiaWQiOiI2NDFmMzAyMmNhMWM5NWZmNTRhNGRlNTYifSwiaWF0IjoxNjc5NzY1NTYyLCJleHAiOjE2Nzk3NjkxNjJ9.4DYxBQRbo3wLcQ3aYoidni-Tl_hRRs-tEAqr0OqlVww
###

POST http://localhost:3000/api/login
Host: localhost:3000
Content-Type: application/json

{
"email": "johndoe@example.comasasd",
"password": "mypasswordasdasd"
}